apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-new-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: kubernetes.gatherloop.co
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: kubernetes-bootcamp
                port:
                  number: 8080
    - host: gatherloop.co
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: gatherloop-landing-page-service
                port:
                  number: 80
